import type { NotificationItem } from './types'

export const notificationData: NotificationItem[] = [
  {
    type: 'follow',
    userProfilePicture: '/assets/images/timeline/Shape.png',
    notificationTypeImg: '/assets/images/notification/profile-add.png',
    userDisplayName: 'Pancake guy',
    userName: '@pancakecake',
  },
  {
    type: 'likePost',
    userProfilePicture: '/assets/images/timeline/Shape.png',
    notificationTypeImg: '/assets/images/notification/heart.png',
    userDisplayName: 'Pancake guy',
    userName: '@pancakecake',
    post: '"Passionate NFT holder exploring the future of digital ownership. Join me in discovering the limitless possibilities of the NFT ecosystem."',
  },
  {
    type: 'reply',
    userProfilePicture: '/assets/images/timeline/Shape.png',
    notificationTypeImg: '/assets/images/notification/message-text.png',
    userDisplayName: 'Pancake guy',
    userName: '@pancakecake',
    comment: `"that's nice dude"`,
  },
  {
    type: 'comment',
    userProfilePicture: '/assets/images/timeline/Shape.png',
    notificationTypeImg: '/assets/images/notification/message-text.png',
    userDisplayName: 'Pancake guy',
    userName: '@pancakecake',
    comment: `"that's nice dude"`,
  },
  {
    type: 'mention',
    userProfilePicture: '/assets/images/timeline/Shape.png',
    notificationTypeImg: '/assets/images/notification/@.png',
    userDisplayName: 'Pancake guy',
    userName: '@pancakecake',
    comment: '"Hey @username, check out this new NFT!"',
  },
  {
    type: 'retweet',
    userProfilePicture: '/assets/images/timeline/Shape.png',
    notificationTypeImg: '/assets/images/notification/repeat.png',
    userDisplayName: 'Pancake guy',
    userName: '@pancakecake',
    post: '"Exploring the future of digital ownership with NFTs!"',
  },
  {
    type: 'clap',
    userProfilePicture: '/assets/images/timeline/Shape.png',
    notificationTypeImg: '/assets/images/notification/Vector.png',
    userDisplayName: 'Pancake guy',
    userName: '@pancakecake',
    post: '"Passionate NFT holder exploring the future of digital ownership. Join me in discovering the limitless possibilities of the NFT ecosystem."',
  },
  {
    type: 'likeNft',
    userProfilePicture: '/assets/images/timeline/Shape.png',
    notificationTypeImg: '/assets/images/notification/heart.png',
    userDisplayName: 'Pancake guy',
    userName: '@pancakecake',
    nftImage: '/assets/images/timeline/Oval.png',
    nftName: 'Bored Ape',
  },
  {
    type: 'personalNewBadge',
    userProfilePicture: '/assets/images/info/card2/card2-2.png',
    notificationTypeImg: '',
    userDisplayName: '',
    userName: '',
  },
  {
    type: 'followerNewBadge',
    userProfilePicture: '/assets/images/timeline/Shape.png',
    notificationTypeImg: '/assets/images/info/card2/card2-2.png',
    userDisplayName: '',
    userName: '@pancakeguy',
  },
  {
    type: 'personalNewExperience',
    userProfilePicture: '/assets/images/notification/briefcase.png',
    notificationTypeImg: '',
    userDisplayName: '',
    userName: '',
  },
  {
    type: 'followerExperience',
    userProfilePicture: '/assets/images/timeline/Shape.png',
    notificationTypeImg: '/assets/images/notification/briefcase.png',
    userDisplayName: '',
    userName: '@username',
  },
  {
    type: 'featureReminder',
    userProfilePicture: '/assets/images/notification/feature-reminder.png',
    notificationTypeImg: '',
    userDisplayName: '',
    userName: '@username',
  },
  {
    type: 'postReminder',
    userProfilePicture: '/assets/images/notification/document.png',
    notificationTypeImg: '',
    userDisplayName: '',
    userName: '@username',
  },
]
